Vagrant.configure("2") do |config|

#scripting manager vm
config.vm.define "managesrvr" do |managesrvr|
    managesrvr.vm.box = "geerlingguy/centos7"
    managesrvr.vm.hostname = "managesrvr"
    managesrvr.vm.network "private_network", ip: "192.168.33.15"
   # manager.vm.synced_folder "../vro-datadir", "/vm_data"
   end

#web server nyngix 1
  config.vm.define "websrvr01" do |websrvr01|
    websrvr01.vm.box = "geerlingguy/centos7"
    websrvr01.vm.hostname = "webber01"
    websrvr01.vm.network "private_network", ip: "192.168.33.16"
   # websrvr01.vm.synced_folder "../vro-datadir", "/vm_data"
   # websrvr01.vm.network "forwarded_port", guest:80, host:9080, host_ip: "127.0.0.1" 
   # websrvr01.vm.provision "shell", inline: <<-SHELL
   #  apt update
   #  apt install apache2 wget unzip -y
   #  systemctl start apache2
   #  systemctl enable apache2
   #  wget https://www.tooplate.com/zip-templates/2108_dashboard.zip
   #  unzip -o 2108_dashboard.zip
   #  cp -r 2108_dashboard/* /var/www/html/
   #  systemctl restart apache2
   # SHELL
  end
  
#web server nyngix 2
  config.vm.define "websrvr02" do |websrvr02|
    websrvr02.vm.box = "geerlingguy/centos7"
    websrvr02.vm.hostname = "webber02"
    websrvr02.vm.network "private_network", ip: "192.168.33.17"
    # websrvr02.vm.synced_folder "../vro-datadir", "/vm_data"
  end

   config.vm.define "cntrlsrvr" do |cntrlsrvr|
	cntrlsrvr.vm.box = "ubuntu/bionic64"
	cntrlsrvr.vm.hostname = "cntrlsrvr01"
	cntrlsrvr.vm.network "private_network", ip: "192.168.33.18"
	  # manager.vm.synced_folder "../vro-datadir", "/vm_data"
  end

   config.vm.define "dbsrvr" do |dbsrvr|
    dbsrvr.vm.box = "geerlingguy/centos7"
    dbsrvr.vm.hostname = "dbsrvr01"
    dbsrvr.vm.network "private_network", ip: "192.168.33.19"
   # manager.vm.synced_folder "../vro-datadir", "/vm_data"
  end

end
